### ISSUE TITLE
Eventual Consistency appears twice in navigation

### ISSUE THREAD

**Issue by RubenLaube-Pohto** [mehdihadeli/awesome-software-architecture#97]
https://github.com/mehdihadeli/awesome-software-architecture/blob/6a4c4737e47161a032d3e49155579dfe701af3ed/mkdocs.yml#L236

Super minor, but it seems that the navigation link to Eventual Consistency has been added on two sequential rows 😃

**Comment by mehdihadeli** [comment]
Fixed, thanks for the report.
